# Generated by Django 3.2.7 on 2021-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0004_alter_nodes_type_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='RPO',
            field=models.IntegerField(default=1, help_text='Максимальный период времени, за который могут быть потеряны данные узла', verbose_name='RPO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='RTO',
            field=models.IntegerField(default=1, help_text='Время, в течении которого узел может оставаться недоступным', verbose_name='RTO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='coordX',
            field=models.IntegerField(default=1200, help_text='Координата X', verbose_name='X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='coordY',
            field=models.IntegerField(default=800, help_text='Координата Y', verbose_name='Y'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edges',
            name='id_gr',
            field=models.CharField(help_text='id ребра', max_length=10, verbose_name='idgr'),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='id_gr',
            field=models.CharField(help_text='id вершины', max_length=10, verbose_name='idgr'),
        ),
    ]
