# Generated by Django 3.2.7 on 2021-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0005_auto_20210923_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='edges',
            name='color',
            field=models.CharField(default='red', help_text='Цвет', max_length=100, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodes',
            name='color',
            field=models.CharField(default='red', help_text='Цвет', max_length=100, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodes',
            name='label_gr',
            field=models.CharField(help_text='Название вершины', max_length=250, verbose_name='label'),
        ),
    ]
