# Generated by Django 3.2.7 on 2021-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0006_auto_20210923_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gr', models.CharField(help_text='id вершины', max_length=10, verbose_name='idgr')),
                ('access', models.IntegerField(help_text='Доступность', verbose_name='access')),
                ('stead', models.FloatField(help_text='Устойчивость', verbose_name='stead')),
                ('costdown', models.FloatField(help_text='Стоимость простоя', verbose_name='costdown')),
                ('RTO', models.IntegerField(help_text='Время, в течении которого узел может оставаться недоступным', verbose_name='RTO')),
                ('RPO', models.IntegerField(help_text='Максимальный период времени, за который могут быть потеряны данные узла', verbose_name='RPO')),
            ],
            options={
                'verbose_name': 'Запись показателей метрик тетсового примера',
                'verbose_name_plural': 'Записи тестовый примера',
            },
        ),
    ]
