# Generated by Django 3.2.7 on 2021-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visstability', '0008_auto_20210924_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edges',
            name='color',
            field=models.CharField(default='red', help_text='Цвет', max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='edges',
            name='weight',
            field=models.FloatField(default=1, help_text='Весм вершины', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='testcasenodes',
            name='RPO',
            field=models.IntegerField(default=1, help_text='Максимальный период времени, за который могут быть потеряны данные узла', verbose_name='RPO'),
        ),
        migrations.AlterField(
            model_name='testcasenodes',
            name='RTO',
            field=models.IntegerField(default=1, help_text='Время, в течении которого узел может оставаться недоступным', verbose_name='RTO'),
        ),
        migrations.AlterField(
            model_name='testcasenodes',
            name='access',
            field=models.IntegerField(default=1, help_text='Доступность', verbose_name='access'),
        ),
        migrations.AlterField(
            model_name='testcasenodes',
            name='costdown',
            field=models.FloatField(default=1, help_text='Стоимость простоя', verbose_name='costdown'),
        ),
        migrations.AlterField(
            model_name='testcasenodes',
            name='stead',
            field=models.FloatField(default=1, help_text='Устойчивость', verbose_name='stead'),
        ),
    ]
